/+
    OpenGL loader generated by glad 0.1.28 on Thu Dec 13 11:57:17 2018.

    Language/Generator: D
    Specification: gl
    APIs: gl=3.3
    Profile: core
    Extensions:
        GL_AMD_debug_output,
        GL_ARB_debug_output,
        GL_KHR_debug
    Loader: True
    Local files: False
    Omit khrplatform: False
    Reproducible: False

    Commandline:
        --profile="core" --api="gl=3.3" --generator="d" --spec="gl" --extensions="GL_AMD_debug_output,GL_ARB_debug_output,GL_KHR_debug"
    Online:
        https://glad.dav1d.de/#profile=core&language=d&specification=gl&loader=on&api=gl%3D3.3&extensions=GL_AMD_debug_output&extensions=GL_ARB_debug_output&extensions=GL_KHR_debug
+/
module blendui.graphics.gl;

public import blendui.graphics.gl.funcs;
public import blendui.graphics.gl.ext;
public import blendui.graphics.gl.enums;
public import blendui.graphics.gl.types;
